server:
  port: ":8080"
  readtimeout: "15s"
  writetimeout: "15s"
  idletimeout: "60s"

files:
  productsfile: "/Users/ravibandhu/personal/go/oolio-food-ordering/data/products.json"
  couponsdir: "/Users/ravibandhu/personal/go/oolio-food-ordering/data/coupons"

logging:
  level: "info"
  format: "json" 